# Generated by Django 5.2.15 on 2026-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_sku_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement_note',
            field=models.TextField(blank=True),
        ),
    ]
