# Generated by Django 5.2.15 on 2026-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_measurement_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual_upi', 'Manual UPI'), ('razorpay', 'Razorpay'), ('cash_on_delivery', 'Cash on Delivery')], default='manual_upi', max_length=20),
        ),
    ]
