# Generated by Django 5.2.15 on 2026-07-09 07:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_armhole',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='default_bicep',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='default_chest',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='default_length',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='default_opening',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='default_waist',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_guide_image',
            field=models.ImageField(blank=True, null=True, upload_to='measurement-guides/'),
        ),
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_phone', models.CharField(max_length=40)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=6)),
                ('armhole', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bicep', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customization_requests', to='store.product')),
            ],
        ),
    ]
